server:
  port: 9000


spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:13306/notice-board
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:13306/notice-board
    username: root
    password: pwd123

logging:
  level:
    root: INFO
    com.mmdev.noticeboard.mapper: DEBUG
  file:
    path: logs