server:
  port: 9009


spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:13306/notice-board
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://127.0.0.1:13306/notice-board
    username: root
    password: pwd123

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /Users/kmj/upload_local/
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: INFO
    com.mmdev.noticeboard: DEBUG
  file:
    path: logs